# This file was generated by GoReleaser. DO NOT EDIT.
class Qbec < Formula
  desc "Qbec (pronounced like the Canadian province) is a CLI tool that allows you to create Kubernetes objects on multiple Kubernetes clusters or namespaces configured correctly for the target environment in question."
  homepage "https://qbec.io/"
  version "0.10.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/splunk/qbec/releases/download/v0.10.3/qbec-darwin-amd64.tar.gz"
    sha256 "98106d118ee1b6630b7c7ccbc7f69012f54834fed29ebdfa526a2000a2a2be33"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/splunk/qbec/releases/download/v0.10.3/qbec-linux-amd64.tar.gz"
      sha256 "ff2ca2421ab35e73c37a2cd5c01b185738f6e7c03397b132e69094fd3198b604"
    end
  end

  def install
    bin.install "qbec"
  end

  test do
    system "#{bin}/qbec version"
  end
end
